#!/bin/sh
#ls css/app.scss | entr css/app.scss sass css/app.scss:../../web/css/app.css &
ls css/app.scss | entr sassc css/app.scss ../../web/css/app.css &
#find js/ -name "*.js" | entr ./extract &
find js/ -name "*.js" | entr ./node_modules/@babel/cli/bin/babel.js js --out-dir ../../web/js &
ls *.xhtml | entr cp -v /_ ../../web
#./node_modules/requirejs/bin/r.js -o build.js
#./extract
